'use client'; // This layout uses client-side hooks and event listeners

import React, { useState } from 'react';
import Image from "next/image";
import GooeyNav from "@/blocks/Components/GooeyNav/GooeyNav";
import { usePathname } from 'next/navigation';
// Import the Link component from next/link
import Link from 'next/link';


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { gilroy } from "@/fonts/fonts";

// Define items for GooeyNav (moved from page.tsx)
const items = [
  { label: "Home", href: "/" },
  { label: "About", href: "/#about" },
  { label: "Projects", href: "/#projects" },
  { label: "Contact", href: "/Contact" },
];

// Pre-filled Gmail compose template
const GMAIL_SUBJECT = encodeURIComponent("Peluang Kolaborasi / Kerja Sama - Zul Tiandra Rifandy");
const GMAIL_BODY = encodeURIComponent("Halo Zul,\n\nSaya tertarik dengan profil dan portofolio Anda, serta ingin berdiskusi lebih lanjut mengenai peluang kerja sama atau proyek.\n\n- Perusahaan / Klien: \n- Topik / Posisi: \n- Pesan: \n\nTerima kasih,\n");

// Define social media links and icon paths
const socialLinks = [
  { platform: "GitHub", href: "https://github.com/RifandyZUl", iconPath: "/icons/github_icon.svg" },
  { platform: "LinkedIn", href: "https://www.linkedin.com/in/zul-tiandra-rifandy/", iconPath: "/icons/linkedin_icon.svg" },
  { platform: "Gmail", href: `https://mail.google.com/mail/?view=cm&fs=1&to=rzultiandra@gmail.com&su=${GMAIL_SUBJECT}&body=${GMAIL_BODY}`, iconPath: "/icons/gmail_icon.svg" },
  { platform: "Resume (CV)", href: "/cv/CV_Zul_Tiandra_Rifandy.pdf", iconPath: "/icons/cv_icon.svg" },
];


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata is for server components, so it stays outside the client component export
// It should ideally be in a separate metadata.ts file in App Router client components
// Keeping it commented out as in your provided code.
/*
  // app/metadata.ts
  import type { Metadata } from 'next';

  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
*/


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // State for mobile menu (moved from page.tsx)
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  // Get current pathname
  const pathname = usePathname();

  // Calculate active index based on pathname
  const activeIndex = items.findIndex(item => item.href === pathname);




  return (
    <html lang="en">
      <head>
        <title>Zul Tiandra Rifandy | AI &amp; Software Engineer</title>
        <meta name="description" content="Portofolio Zul Tiandra Rifandy — AI/Machine Learning Engineer & Full Stack Software Developer, spesialis Deep Learning, Computer Vision, dan Sistem Terdistribusi." />
      </head>
      <body
        // Added bg-black class for black background
        className={`${geistSans.variable} ${geistMono.variable} ${gilroy.variable} antialiased font-gilroy bg-black`}
      >
        {/* Header Section */}
        {/* Adjusted padding for different screen sizes */}
        <header className="sticky top-0 z-50 flex w-full items-center justify-between px-4 py-2 md:px-8 md:py-3 bg-transparent backdrop-blur-[3px]">
          {/* Logo */}
          {/* Using Link for Logo if it navigates to home */}
          {/* Adjusted margin for different screen sizes */}
            <Link href="/" passHref>
             <Image
                src="/logo/lauv-logo2.svg"
                alt="Zul Logo"
                width={35} // Base size for logo
                height={35} // Base size for logo
                // Added responsive sizing for the logo image itself if needed (optional, depends on design)
                // className="w-8 h-8 sm:w-9 sm:h-9 md:w-10 md:h-10 m-4 md:m-10 transition-all duration-300 hover:scale-150 hover:rotate-10 hover:brightness-125"
                className="m-4 md:m-10 transition-all duration-300 hover:scale-150 hover:rotate-10 hover:brightness-125" // Adjusted margin
             />
            </Link>


          {/* Desktop Navigation - hidden on small screens */}
          {/* Container with fixed dimensions - GooeyNav should handle internal responsiveness */}
          <div className="hidden md:block font-medium" style={{ height: '70px', width: '480px', position: 'relative' }}>
            <GooeyNav
              items={items} // The items array contains { label, href }
              particleCount={6}
              particleDistances={[90, 10]}
              particleR={100}
              initialActiveIndex={activeIndex !== -1 ? activeIndex : 0} // Set dynamically, default to 0 if not found
              animationTime={600}
              timeVariance={300}
              colors={[1, 2, 3, 1, 2, 3, 1, 4]}
              // IMPORTANT: The GooeyNav component itself needs to use <Link> internally for its items
            />
          </div>

          {/* Hamburger button - visible only on small screens */}
          <button
            className="md:hidden text-white p-2 focus:outline-none"
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Toggle mobile menu" // Added accessibility label
          >
            {/* Hamburger icon lines */}
            {/* Added transition for animation if you want to animate the icon */}
            <div className="w-6 h-0.5 bg-white mb-1.5 transition-all duration-300 ease-in-out"></div>
            <div className="w-6 h-0.5 bg-white mb-1.5 transition-all duration-300 ease-in-out"></div>
            <div className="w-6 h-0.5 bg-white transition-all duration-300 ease-in-out"></div>
          </button>
        </header>

        {/* Mobile menu - only visible when mobileMenuOpen is true */}
        {/* Positioned fixed below the header, covers full width on mobile */}
        {mobileMenuOpen && (
          // Changed position from absolute to fixed
          // Adjusted top position to match header height at different breakpoints
          // Added overflow-y-auto to allow scrolling if the menu content is taller than the viewport
          <div className="md:hidden bg-transparent backdrop-blur-[10px] pt-10 fixed top-[72px] sm:top-[80px] md:top-[96px] right-0 left-0 z-40 p-4 sm:p-5 overflow-y-auto h-[calc(100vh - 72px)] sm:h-[calc(100vh - 80px)] md:h-[calc(100vh - 96px)]"> {/* Adjusted top position, added overflow-y-auto and height */}
            <nav className="flex flex-col space-y-4">
              {items.map((item, index) => (
                // Using <Link> for navigation items
                <Link
                  key={index}
                  href={item.href}
                  prefetch={true}
                  className="text-white hover:text-gray-300 py-2 px-4 font-medium text-base sm:text-lg"
                  onClick={(e) => {
                    setMobileMenuOpen(false);
                    if (item.href.includes('#') && pathname === '/') {
                      const hash = item.href.substring(item.href.indexOf('#') + 1);
                      const el = document.getElementById(hash);
                      if (el) {
                        e.preventDefault();
                        el.scrollIntoView({ behavior: 'smooth', block: 'start' });
                      }
                    }
                  }}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
          </div>
        )}
        {/* End Header Section */}

        {children} {/* This is where your page content (like page.tsx) will be rendered */}

        {/* Sticky Social Media Container */}
        {/* Positioned fixed to the bottom right */}
        {/* Added responsive padding, rounded corners, border, and background */}
        <div className="fixed bottom-4 right-4 md:bottom-8 md:right-8 z-50 bg-black/60 border border-white/[.30] border-dashed rounded-full p-2 md:p-4 flex flex-col items-center space-y-7 md:space-y-5">
          {socialLinks.map((link) => (
            <a
              key={link.platform}
              href={link.href}
              target="_blank"
              rel="noopener noreferrer"
              className="transition-transform duration-200 hover:scale-110"
              aria-label={link.platform}
              title={link.platform}
            >
              {/* Social media icon image */}
              <Image
                src={link.iconPath} // Use the icon path from the socialLinks array
                alt={`${link.platform} icon`}
                width={20} // Base size for mobile
                height={20} // Base size for mobile
                unoptimized
                className="w-5 h-5 sm:w-6 sm:h-6 md:w-7 md:h-7 object-contain" // Responsive size and object-contain
              />
            </a>
          ))}
        </div>
        {/* End Sticky Social Media Container */}

      </body>
    </html>
  );
}
